### ISSUE TITLE
Test Docker image creation in CI

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/playground-lingua-franca#65]
There are currently errors occurring in the Docker image creation. We need to catch these in CI.

**Comment by axmmisaka** [comment]
See #68

**Comment by akihitoiwai0912** [comment]
I encounted same problem on Docker creation. My creation log says:

```
2023-07-25 04:31:55.006Z: bash -i ./utils/scripts/setup-user-env.bash && bash ./utils/scripts/setup-lf.bash stable
2023-07-25 04:31:55.267Z: postCreateCommand failed with exit code 126. Skipping any further user-provided commands.

2023-07-25 04:31:55.270Z: Error: Command failed: /bin/sh -c bash -i ./utils/scripts/setup-user-env.bash && bash ./utils/scripts/setup-lf.bash stable
2023-07-25 04:31:55.271Z:     at k8 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1780:130)
2023-07-25 04:31:55.272Z:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-07-25 04:31:55.273Z:     at async W0 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1772:4434)
2023-07-25 04:31:55.273Z:     at async V0 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1772:3779)
2023-07-25 04:31:55.274Z:     at async z0 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1772:2983)
2023-07-25 04:31:55.275Z:     at async Xa (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1772:2427)
2023-07-25 04:31:55.276Z:     at async Lte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2007:1346)
2023-07-25 04:31:55.277Z:     at async e3 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2007:964)
2023-07-25 04:31:55.278Z:     at async Qte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2024:3660)
2023-07-25 04:31:55.279Z:     at async Kf (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2024:4775)
2023-07-25 04:31:55.279Z: {"outcome":"error","message":"Command failed: /bin/sh -c bash -i ./utils/scripts/setup-user-env.bash && bash ./utils/scripts/setup-lf.bash stable","description":"The postCreateCommand in the devcontainer.json failed.","containerId":"26c270745c4304f0d64332bc4b244929fbe8b54aa78dbea0e865affa0de2d6c4"}
2023-07-25 04:31:55.280Z: devcontainer process exited with exit code 1

====================================== ERROR ====================================
2023-07-25 04:31:55.281Z: Failed to create container.
=================================================================================
```

**Comment by lhstrh** [comment]
Thanks, @akihitoiwai0912. We're working on a fix!
